### PR TITLE
Fix previous merge

### PR DESCRIPTION
**Pull request by fake-name**
Ok, my previous PR was in fact broken (travis was correct). 

Pytest was picking up the system installed version of the package. Apparently it doesn't see the package from the working directory, unlike how `nose` works. Basically, I was testing the released 0.5.0 version.

Anyways, it now passes all the tests, and is actually functional.

### CODE REVIEW

**Comment by fake-name** [comment]
Friggin finally. Let me see if I can fix https://github.com/item4/ugoira/issues/5

**Comment by item4** [comment]
👍

**Comment by fake-name** [comment]
FWIW, apparently the tests issue was running `pytest -v --cov ./` vs `python3 -m pytest -v --cov ./` The former doesn't see any modules in the CWD (I think it is actually executed from the directory where the `pytest` script is).

`python3 -m pytest -v --cov ./` will load tests from the CWD first, which is now nose works.

**Comment by item4** [comment]
this pr was released by 0.6.0 version

**Comment by fake-name** [comment]
Awesomesauce!

**Pull request merged**
