### PR TITLE
Allow multiple downloads at once

### PR DESCRIPTION
**Pull request by ThisIsPIRI**
I replaced the mock files because the old image was deleted and the old file made tests fail for some reason. Not sure how best to test this. Probably not [something like this](https://github.com/ThisIsPIRI/ugoira/commit/c7528d9f68b4d8529b7feb5b558e6338c66a70fd)

### CODE REVIEW

**Comment by ThisIsPIRI** [comment]
I can't find any trailing whitespace despite Travis saying otherwise.

**Comment by item4** [comment]
Grea!!  Thanks for your contribution!

**Comment by item4** [comment]
@ThisIsPIRI I will release new version after #3 merged.

**Comment by item4** [comment]
@ThisIsPIRI sorry for late. I just released now.

**Pull request merged**
